name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: rustup toolchain install
      run: |
        rustup target add x86_64-pc-windows-gnu
        sudo apt install --no-install-recommends -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu





